name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - triton-mlir

jobs:

  Runner-Preparation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Prepare runner matrix
      id: set-matrix
      run: |
        if [ x"${{ github.repository }}" == x"openai/triton" ]; then
          echo '::set-output name=matrix::[["self-hosted", "A10"], "ubuntu-latest", "macos-latest"]'
        elif [ x"${{ github.repository }}" == x"shintaro-iwasaki/triton" ]; then
          echo '::set-output name=matrix::[["self-hosted", "A10"], ["self-hosted", "B10"], "ubuntu-latest", "macos-latest"]'
        else
          echo '::set-output name=matrix::["ubuntu-latest", "macos-latest"]'
        fi

  Integration-Tests:
    needs: Runner-Preparation

    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: ${{fromJson(needs.Runner-Preparation.outputs.matrix)}}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear cache
        run: |
          rm -rf ~/.triton/cache/

      - name: Execute something only on self-hosted
        if: ${{ matrix.runner[0] == 'self-hosted' }}
        run: |
          echo "ABC"

      - name: Execute something only when runner == macos-latest
        if: ${{ matrix.runner == 'macos-latest' }}
        run: |
          echo "ABC"

      - name: Execute something only when runner != macos-latest
        if: ${{ matrix.runner != 'macos-latest' }}
        run: |
          echo "ABC"
